name = "Triopack"
author = "Christian Murray"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0420ceaf3c4b5e0500ce4cd0898e289faf3124cc65d587fa6e4427416eceb62"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
