name = "Triopack"
author = "Christian Murray"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe1e8540445442a8f5acc41c490476cde22fe582ae24215579047f36e3443430"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
