name = "Triopack"
author = "Christian Murray"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a617c1c78dd92b87774df68fd8eb3b7b9f01bd1f62944b86b100c1264bcb15b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
